// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Gauntlet;

  Gauntlet = (function() {
    function Gauntlet() {}

    Gauntlet.version = '0.0.2';

    Gauntlet.isServer = typeof window === 'undefined';

    return Gauntlet;

  })();

  Gauntlet.Events = require('./gauntlet_events');

  Gauntlet.Promise = require('./gauntlet_promise');

  module.exports = Gauntlet;

  Gauntlet.Adaptor = require('./gauntlet_adaptor');

}).call(this);
