// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var Gauntlet;

  Gauntlet = (function() {
    function Gauntlet() {}

    Gauntlet.version = '0.0.1';

    Gauntlet.Events = require('./gauntlet_events');

    Gauntlet.Promise = require('./gauntlet_promise');

    return Gauntlet;

  })();

  module.exports = Gauntlet;

}).call(this);
